#pragma once

#include <vector>
#include <string>
#include <cstdint>

#include "irrlicht.h"

#include "cereal/cereal.hpp"
#include "cereal/archives/xml.hpp"
#include "cereal/types/vector.hpp"
#include "cereal/types/string.hpp"

// ---------------------------------------------------------------------------
// CSG brush authoring data.
//
// The plane set (BrushFace::planePoints) is the permanent source of truth for
// level geometry.  Vertices, loops, bounds and the compiled chunk meshes are
// all derived caches, regenerated by BrushGeometry / BrushCompiler.  Plane
// points are stored as three CCW points (TrenchBroom-style) rather than
// normal+d so quantizing them to the grid on every commit bounds float drift.
// ---------------------------------------------------------------------------

enum BrushFaceFlags : irr::u8
{
    FACE_NODRAW = 1 << 0,   // excluded from render buffers; still emits collision
};

enum BrushSolidClass : irr::u8
{
    SOLID_WORLD  = 0,       // static world geometry, chunk-batched
    SOLID_DETAIL = 1,       // reserved
    SOLID_ENTITY = 2,       // mover source brush: owned by the entity named in
                            // Brush::owner, excluded from every static-world
                            // pipeline (chunks/collision/nav/lightmaps/picking)
};

// Per-brush content semantics.  0 = normal structural brush (renders, blocks
// everything).  Any nonzero value makes the brush a "tool brush": stripped
// from the runtime render mesh at compile time, still fully editable and
// pickable in the editor.  Bits combine freely (e.g. monster+weapon clip).
enum BrushContentFlags : irr::u32
{
    CONTENT_CLIP_PLAYER  = 1 << 0,  // blocks player movement (CCT filter)
    CONTENT_CLIP_MONSTER = 1 << 1,  // blocks NPC movement probes
    CONTENT_CLIP_WEAPON  = 1 << 2,  // blocks weapon hitscans (inert until rays move to PhysX)
    CONTENT_TRIGGER      = 1 << 3,  // fires `receiver` entity list on player overlap
    CONTENT_SKY          = 1 << 4,  // sky marker; no runtime behavior in v1
    CONTENT_TRIGGER_ONCE = 1 << 5,  // modifier on CONTENT_TRIGGER: fire once per session
    CONTENT_LADDER       = 1 << 6,  // player can climb while overlapping the volume
    CONTENT_FOG          = 1 << 7,  // overrides scene fog while the player is inside the volume
    CONTENT_HURT         = 1 << 8,  // damages the player continuously while inside the volume

    CONTENT_CLIP_MASK = CONTENT_CLIP_PLAYER | CONTENT_CLIP_MONSTER | CONTENT_CLIP_WEAPON,
};

// brushes.xml schema version, written as a <version> header element by
// BrushManager::serialize.  Files without the element load as version 0.
// v1: contentFlags + receiver.  v2: owner (mover brushes).  v3: fog-zone params.
// v4: per-face displacement (DispInfo).  v5: hurt-volume damage rate.
constexpr uint32_t BRUSHES_XML_VERSION = 5;

// ---------------------------------------------------------------------------
// Per-face displacement surface (Source/Hammer style).  Attached to a QUAD
// face; subdivides it into a (side x side) grid and stores a per-vertex offset
// from the flat base position.  The base grid is derived at compile time from
// the face's four corners via BrushGeometry::dispBasePos (parameterized on the
// face's uAxis/vAxis), so offsets are relative and survive face push/pull.
// Only this authoring data is persisted; the tessellated mesh + smooth normals
// are rebuilt by BrushCompiler.  Offsets are full 3D (not scalar-along-normal)
// so mild overhangs are possible; a single face still cannot fold fully back.
// ---------------------------------------------------------------------------
struct DispInfo
{
    irr::u8 power = 0;                   // 0 = none; 2/3/4 -> side 5/9/17
    std::vector<float> offsets;          // interleaved x,y,z, size 3*side()*side()

    int  side()   const { return (1 << power) + 1; }
    int  vertCount() const { return side() * side(); }
    bool active() const { return power >= 2 && offsets.size() == static_cast<size_t>(3 * vertCount()); }

    // Read/write vertex k's offset as a vector3df.
    irr::core::vector3df get(int k) const
    {
        return { offsets[k * 3 + 0], offsets[k * 3 + 1], offsets[k * 3 + 2] };
    }
    void set(int k, const irr::core::vector3df& v)
    {
        offsets[k * 3 + 0] = v.X; offsets[k * 3 + 1] = v.Y; offsets[k * 3 + 2] = v.Z;
    }
};

struct BrushFace
{
    // ---- persistent ----
    // Three points defining the plane, wound so the plane normal faces OUT of
    // the brush.  Snapped to BrushGeometry::GRID_QUANTUM on every edit commit.
    irr::core::vector3df planePoints[3];

    std::string materialName;                       // texture path, same convention as StaticProp::textures
    std::string shaderName = "phong_perpixel";      // ShaderMaterialManager key

    // Valve-220 style projection: explicit world-space UV axes, independent of
    // the plane so textures stay put under vertex drags (texture lock).
    // UV emission: u = (dot(p, uAxis) + shiftU) / scaleU — scale is WORLD
    // UNITS PER TEXTURE REPEAT (no texture-pixel-size dependence), shift is a
    // world-unit offset along the axis.
    irr::core::vector3df uAxis = { 1.f, 0.f, 0.f };
    irr::core::vector3df vAxis = { 0.f, 0.f, 1.f };
    float shiftU = 0.0f, shiftV = 0.0f;             // world units along uAxis/vAxis
    float scaleU = 2.0f, scaleV = 2.0f;             // world units per texture repeat
    float rotationDeg = 0.0f;                       // UI echo only; axes are authoritative

    irr::u8 flags = 0;                              // BrushFaceFlags

    DispInfo disp;                                  // v4: displacement (power 0 = none)

    // ---- derived (rebuilt by BrushGeometry::rebuild, never serialized) ----
    irr::core::plane3df plane;                      // normalized, outward-facing
    std::vector<irr::u16> loop;                     // vertex indices into Brush::verts,
                                                    // angle-sorted for front-facing fans

    template<class Archive>
    void save(Archive& ar) const
    {
        ar(cereal::make_nvp("p0x", planePoints[0].X), cereal::make_nvp("p0y", planePoints[0].Y), cereal::make_nvp("p0z", planePoints[0].Z),
           cereal::make_nvp("p1x", planePoints[1].X), cereal::make_nvp("p1y", planePoints[1].Y), cereal::make_nvp("p1z", planePoints[1].Z),
           cereal::make_nvp("p2x", planePoints[2].X), cereal::make_nvp("p2y", planePoints[2].Y), cereal::make_nvp("p2z", planePoints[2].Z),
           CEREAL_NVP(materialName),
           CEREAL_NVP(shaderName),
           cereal::make_nvp("uax", uAxis.X), cereal::make_nvp("uay", uAxis.Y), cereal::make_nvp("uaz", uAxis.Z),
           cereal::make_nvp("vax", vAxis.X), cereal::make_nvp("vay", vAxis.Y), cereal::make_nvp("vaz", vAxis.Z),
           CEREAL_NVP(shiftU), CEREAL_NVP(shiftV),
           CEREAL_NVP(scaleU), CEREAL_NVP(scaleV),
           CEREAL_NVP(rotationDeg),
           CEREAL_NVP(flags));
    }

    template<class Archive>
    void load(Archive& ar)
    {
        ar(cereal::make_nvp("p0x", planePoints[0].X), cereal::make_nvp("p0y", planePoints[0].Y), cereal::make_nvp("p0z", planePoints[0].Z),
           cereal::make_nvp("p1x", planePoints[1].X), cereal::make_nvp("p1y", planePoints[1].Y), cereal::make_nvp("p1z", planePoints[1].Z),
           cereal::make_nvp("p2x", planePoints[2].X), cereal::make_nvp("p2y", planePoints[2].Y), cereal::make_nvp("p2z", planePoints[2].Z),
           CEREAL_NVP(materialName),
           CEREAL_NVP(shaderName),
           cereal::make_nvp("uax", uAxis.X), cereal::make_nvp("uay", uAxis.Y), cereal::make_nvp("uaz", uAxis.Z),
           cereal::make_nvp("vax", vAxis.X), cereal::make_nvp("vay", vAxis.Y), cereal::make_nvp("vaz", vAxis.Z),
           CEREAL_NVP(shiftU), CEREAL_NVP(shiftV),
           CEREAL_NVP(scaleU), CEREAL_NVP(scaleV),
           CEREAL_NVP(rotationDeg),
           CEREAL_NVP(flags));
    }
};

struct Brush
{
    // ---- persistent ----
    uint32_t    id = 0;                 // stable, assigned by BrushManager, never reused
    std::string name;                   // hierarchy display, defaults to "Brush <id>"
    std::vector<BrushFace> faces;       // 4..MAX_FACES, validated by BrushGeometry
    irr::u8     solidClass = SOLID_WORLD;
    bool        castShadows = true;
    bool        receivesLightmap = true;
    irr::u32    contentFlags = 0;               // BrushContentFlags; 0 = normal structural brush
    std::string receiver;                       // trigger targets: CSV entity names
                                                // (LogicComponent::receiver convention, empty = unset)
    std::string owner;                          // SOLID_ENTITY only: name of the mover entity whose
                                                // mesh this brush compiles into; empty for world brushes

    // CONTENT_FOG: fog values applied while the player is inside this volume,
    // cross-fading back to the scene defaults on exit (GameplaySystem resolve).
    // Pure runtime data — editing these never recompiles the brush geometry.
    float               fogDensity = 0.0f;
    float               fogStart   = 5.0f;
    irr::video::SColorf fogColor   = irr::video::SColorf(0.5f, 0.5f, 0.6f, 1.0f);

    // CONTENT_HURT: damage dealt to the player per second of overlap, applied
    // as whole points once the fractional accumulator crosses 1 (see
    // GameplaySystem::updateBrushVolumes).  Like the fog values this is pure
    // runtime data — editing it never recompiles the brush geometry.
    float               hurtDamagePerSecond = 10.0f;

    // ---- derived (never serialized) ----
    std::vector<irr::core::vector3df> verts;    // welded shared vertex pool
    irr::core::aabbox3df bounds;
    irr::s64    chunkKey = -1;                  // packed cell coords of owning chunk
    bool        geometryValid = false;

    // Runtime trigger state (per play session — brushes are recreated on every
    // scene import, so entering editor-play resets these).
    bool triggerInside = false;                 // player was inside last frame (edge detect)
    bool triggerFired  = false;                 // CONTENT_TRIGGER_ONCE latch
    float hurtAccum    = 0.0f;                  // CONTENT_HURT: sub-point damage carried between frames

    bool isToolBrush() const { return contentFlags != 0; }
    irr::u32 clipMask() const { return contentFlags & CONTENT_CLIP_MASK; }
    bool isMoverBrush() const { return solidClass == SOLID_ENTITY; }

    template<class Archive>
    void save(Archive& ar) const
    {
        ar(CEREAL_NVP(id),
           CEREAL_NVP(name),
           cereal::make_nvp("faceCount", static_cast<uint32_t>(faces.size())));
        for (const auto& f : faces)
            ar(cereal::make_nvp("face", f));
        ar(CEREAL_NVP(solidClass),
           CEREAL_NVP(castShadows),
           CEREAL_NVP(receivesLightmap),
           CEREAL_NVP(contentFlags),
           CEREAL_NVP(receiver),
           CEREAL_NVP(owner),
           CEREAL_NVP(fogDensity),
           CEREAL_NVP(fogStart),
           cereal::make_nvp("fogColorR", fogColor.r),
           cereal::make_nvp("fogColorG", fogColor.g),
           cereal::make_nvp("fogColorB", fogColor.b),
           CEREAL_NVP(hurtDamagePerSecond));

        // v4: displacement is authored per-face but serialized here (Brush has
        // the version).  Write one block per face: a flag, then power+offsets
        // only for displaced faces, so undisplaced faces cost a single bool.
        for (const auto& f : faces)
        {
            const bool hasDisp = f.disp.active();
            ar(cereal::make_nvp("hasDisp", hasDisp));
            if (hasDisp)
                ar(cereal::make_nvp("dispPower", f.disp.power),
                   cereal::make_nvp("dispOffsets", f.disp.offsets));
        }
    }

    // Called manually by BrushManager::deserialize with the file-level schema
    // version (not through cereal's NVP path — versioning needs the argument).
    // version 0 files predate contentFlags/receiver; defaults hold.
    template<class Archive>
    void load(Archive& ar, uint32_t version)
    {
        uint32_t faceCount = 0;
        ar(CEREAL_NVP(id),
           CEREAL_NVP(name),
           cereal::make_nvp("faceCount", faceCount));
        faces.resize(faceCount);
        for (uint32_t i = 0; i < faceCount; i++)
            ar(cereal::make_nvp("face", faces[i]));
        ar(CEREAL_NVP(solidClass),
           CEREAL_NVP(castShadows),
           CEREAL_NVP(receivesLightmap));
        if (version >= 1)
            ar(CEREAL_NVP(contentFlags),
               CEREAL_NVP(receiver));
        if (version >= 2)
            ar(CEREAL_NVP(owner));
        if (version >= 3)
            ar(CEREAL_NVP(fogDensity),
               CEREAL_NVP(fogStart),
               cereal::make_nvp("fogColorR", fogColor.r),
               cereal::make_nvp("fogColorG", fogColor.g),
               cereal::make_nvp("fogColorB", fogColor.b));
        if (version >= 5)
            ar(CEREAL_NVP(hurtDamagePerSecond));

        // v4: one displacement block per face, mirroring save().  Pre-v4 files
        // have none, so every face stays flat (disp.power == 0).
        if (version >= 4)
            for (auto& f : faces)
            {
                bool hasDisp = false;
                ar(cereal::make_nvp("hasDisp", hasDisp));
                if (hasDisp)
                    ar(cereal::make_nvp("dispPower", f.disp.power),
                       cereal::make_nvp("dispOffsets", f.disp.offsets));
            }
    }
};
