#pragma once

#include <vector>
#include <string>
#include <cstdint>

#include "irrlicht.h"

#include "cereal/cereal.hpp"
#include "cereal/archives/xml.hpp"
#include "cereal/types/vector.hpp"
#include "cereal/types/string.hpp"

// ---------------------------------------------------------------------------
// CSG brush authoring data.
//
// The plane set (BrushFace::planePoints) is the permanent source of truth for
// level geometry.  Vertices, loops, bounds and the compiled chunk meshes are
// all derived caches, regenerated by BrushGeometry / BrushCompiler.  Plane
// points are stored as three CCW points (TrenchBroom-style) rather than
// normal+d so quantizing them to the grid on every commit bounds float drift.
// ---------------------------------------------------------------------------

enum BrushFaceFlags : irr::u8
{
    FACE_NODRAW = 1 << 0,   // excluded from render buffers; still emits collision
};

enum BrushSolidClass : irr::u8
{
    SOLID_WORLD = 0,        // static world geometry, chunk-batched (only v1 value)
    // reserved: SOLID_DETAIL, SOLID_ENTITY
};

struct BrushFace
{
    // ---- persistent ----
    // Three points defining the plane, wound so the plane normal faces OUT of
    // the brush.  Snapped to BrushGeometry::GRID_QUANTUM on every edit commit.
    irr::core::vector3df planePoints[3];

    std::string materialName;                       // texture path, same convention as StaticProp::textures
    std::string shaderName = "phong_perpixel";      // ShaderMaterialManager key

    // Valve-220 style projection: explicit world-space UV axes, independent of
    // the plane so textures stay put under vertex drags (texture lock).
    // UV emission: u = (dot(p, uAxis) + shiftU) / scaleU — scale is WORLD
    // UNITS PER TEXTURE REPEAT (no texture-pixel-size dependence), shift is a
    // world-unit offset along the axis.
    irr::core::vector3df uAxis = { 1.f, 0.f, 0.f };
    irr::core::vector3df vAxis = { 0.f, 0.f, 1.f };
    float shiftU = 0.0f, shiftV = 0.0f;             // world units along uAxis/vAxis
    float scaleU = 2.0f, scaleV = 2.0f;             // world units per texture repeat
    float rotationDeg = 0.0f;                       // UI echo only; axes are authoritative

    irr::u8 flags = 0;                              // BrushFaceFlags

    // ---- derived (rebuilt by BrushGeometry::rebuild, never serialized) ----
    irr::core::plane3df plane;                      // normalized, outward-facing
    std::vector<irr::u16> loop;                     // vertex indices into Brush::verts,
                                                    // angle-sorted for front-facing fans

    template<class Archive>
    void save(Archive& ar) const
    {
        ar(cereal::make_nvp("p0x", planePoints[0].X), cereal::make_nvp("p0y", planePoints[0].Y), cereal::make_nvp("p0z", planePoints[0].Z),
           cereal::make_nvp("p1x", planePoints[1].X), cereal::make_nvp("p1y", planePoints[1].Y), cereal::make_nvp("p1z", planePoints[1].Z),
           cereal::make_nvp("p2x", planePoints[2].X), cereal::make_nvp("p2y", planePoints[2].Y), cereal::make_nvp("p2z", planePoints[2].Z),
           CEREAL_NVP(materialName),
           CEREAL_NVP(shaderName),
           cereal::make_nvp("uax", uAxis.X), cereal::make_nvp("uay", uAxis.Y), cereal::make_nvp("uaz", uAxis.Z),
           cereal::make_nvp("vax", vAxis.X), cereal::make_nvp("vay", vAxis.Y), cereal::make_nvp("vaz", vAxis.Z),
           CEREAL_NVP(shiftU), CEREAL_NVP(shiftV),
           CEREAL_NVP(scaleU), CEREAL_NVP(scaleV),
           CEREAL_NVP(rotationDeg),
           CEREAL_NVP(flags));
    }

    template<class Archive>
    void load(Archive& ar)
    {
        ar(cereal::make_nvp("p0x", planePoints[0].X), cereal::make_nvp("p0y", planePoints[0].Y), cereal::make_nvp("p0z", planePoints[0].Z),
           cereal::make_nvp("p1x", planePoints[1].X), cereal::make_nvp("p1y", planePoints[1].Y), cereal::make_nvp("p1z", planePoints[1].Z),
           cereal::make_nvp("p2x", planePoints[2].X), cereal::make_nvp("p2y", planePoints[2].Y), cereal::make_nvp("p2z", planePoints[2].Z),
           CEREAL_NVP(materialName),
           CEREAL_NVP(shaderName),
           cereal::make_nvp("uax", uAxis.X), cereal::make_nvp("uay", uAxis.Y), cereal::make_nvp("uaz", uAxis.Z),
           cereal::make_nvp("vax", vAxis.X), cereal::make_nvp("vay", vAxis.Y), cereal::make_nvp("vaz", vAxis.Z),
           CEREAL_NVP(shiftU), CEREAL_NVP(shiftV),
           CEREAL_NVP(scaleU), CEREAL_NVP(scaleV),
           CEREAL_NVP(rotationDeg),
           CEREAL_NVP(flags));
    }
};

struct Brush
{
    // ---- persistent ----
    uint32_t    id = 0;                 // stable, assigned by BrushManager, never reused
    std::string name;                   // hierarchy display, defaults to "Brush <id>"
    std::vector<BrushFace> faces;       // 4..MAX_FACES, validated by BrushGeometry
    irr::u8     solidClass = SOLID_WORLD;
    bool        castShadows = true;
    bool        receivesLightmap = true;

    // ---- derived (never serialized) ----
    std::vector<irr::core::vector3df> verts;    // welded shared vertex pool
    irr::core::aabbox3df bounds;
    irr::s64    chunkKey = -1;                  // packed cell coords of owning chunk
    bool        geometryValid = false;

    template<class Archive>
    void save(Archive& ar) const
    {
        ar(CEREAL_NVP(id),
           CEREAL_NVP(name),
           cereal::make_nvp("faceCount", static_cast<uint32_t>(faces.size())));
        for (const auto& f : faces)
            ar(cereal::make_nvp("face", f));
        ar(CEREAL_NVP(solidClass),
           CEREAL_NVP(castShadows),
           CEREAL_NVP(receivesLightmap));
    }

    template<class Archive>
    void load(Archive& ar)
    {
        uint32_t faceCount = 0;
        ar(CEREAL_NVP(id),
           CEREAL_NVP(name),
           cereal::make_nvp("faceCount", faceCount));
        faces.resize(faceCount);
        for (uint32_t i = 0; i < faceCount; i++)
            ar(cereal::make_nvp("face", faces[i]));
        ar(CEREAL_NVP(solidClass),
           CEREAL_NVP(castShadows),
           CEREAL_NVP(receivesLightmap));
    }
};
