#pragma once

#include <vector>
#include <string>
#include <cstdint>

#include "irrlicht.h"

#include "cereal/cereal.hpp"
#include "cereal/archives/xml.hpp"
#include "cereal/types/vector.hpp"
#include "cereal/types/string.hpp"

// ---------------------------------------------------------------------------
// CSG brush authoring data.
//
// The plane set (BrushFace::planePoints) is the permanent source of truth for
// level geometry.  Vertices, loops, bounds and the compiled chunk meshes are
// all derived caches, regenerated by BrushGeometry / BrushCompiler.  Plane
// points are stored as three CCW points (TrenchBroom-style) rather than
// normal+d so quantizing them to the grid on every commit bounds float drift.
// ---------------------------------------------------------------------------

enum BrushFaceFlags : irr::u8
{
    FACE_NODRAW = 1 << 0,   // excluded from render buffers; still emits collision
};

enum BrushSolidClass : irr::u8
{
    SOLID_WORLD  = 0,       // static world geometry, chunk-batched
    SOLID_DETAIL = 1,       // reserved
    SOLID_ENTITY = 2,       // mover source brush: owned by the entity named in
                            // Brush::owner, excluded from every static-world
                            // pipeline (chunks/collision/nav/lightmaps/picking)
};

// Per-brush content semantics.  0 = normal structural brush (renders, blocks
// everything).  Any nonzero value makes the brush a "tool brush": stripped
// from the runtime render mesh at compile time, still fully editable and
// pickable in the editor.  Bits combine freely (e.g. monster+weapon clip).
enum BrushContentFlags : irr::u32
{
    CONTENT_CLIP_PLAYER  = 1 << 0,  // blocks player movement (CCT filter)
    CONTENT_CLIP_MONSTER = 1 << 1,  // blocks NPC movement probes
    CONTENT_CLIP_WEAPON  = 1 << 2,  // blocks weapon hitscans (inert until rays move to PhysX)
    CONTENT_TRIGGER      = 1 << 3,  // fires `receiver` entity list on player overlap
    CONTENT_SKY          = 1 << 4,  // sky marker; no runtime behavior in v1
    CONTENT_TRIGGER_ONCE = 1 << 5,  // modifier on CONTENT_TRIGGER: fire once per session
    CONTENT_LADDER       = 1 << 6,  // player can climb while overlapping the volume

    CONTENT_CLIP_MASK = CONTENT_CLIP_PLAYER | CONTENT_CLIP_MONSTER | CONTENT_CLIP_WEAPON,
};

// brushes.xml schema version, written as a <version> header element by
// BrushManager::serialize.  Files without the element load as version 0.
// v1: contentFlags + receiver.  v2: owner (mover brushes).
constexpr uint32_t BRUSHES_XML_VERSION = 2;

struct BrushFace
{
    // ---- persistent ----
    // Three points defining the plane, wound so the plane normal faces OUT of
    // the brush.  Snapped to BrushGeometry::GRID_QUANTUM on every edit commit.
    irr::core::vector3df planePoints[3];

    std::string materialName;                       // texture path, same convention as StaticProp::textures
    std::string shaderName = "phong_perpixel";      // ShaderMaterialManager key

    // Valve-220 style projection: explicit world-space UV axes, independent of
    // the plane so textures stay put under vertex drags (texture lock).
    // UV emission: u = (dot(p, uAxis) + shiftU) / scaleU — scale is WORLD
    // UNITS PER TEXTURE REPEAT (no texture-pixel-size dependence), shift is a
    // world-unit offset along the axis.
    irr::core::vector3df uAxis = { 1.f, 0.f, 0.f };
    irr::core::vector3df vAxis = { 0.f, 0.f, 1.f };
    float shiftU = 0.0f, shiftV = 0.0f;             // world units along uAxis/vAxis
    float scaleU = 2.0f, scaleV = 2.0f;             // world units per texture repeat
    float rotationDeg = 0.0f;                       // UI echo only; axes are authoritative

    irr::u8 flags = 0;                              // BrushFaceFlags

    // ---- derived (rebuilt by BrushGeometry::rebuild, never serialized) ----
    irr::core::plane3df plane;                      // normalized, outward-facing
    std::vector<irr::u16> loop;                     // vertex indices into Brush::verts,
                                                    // angle-sorted for front-facing fans

    template<class Archive>
    void save(Archive& ar) const
    {
        ar(cereal::make_nvp("p0x", planePoints[0].X), cereal::make_nvp("p0y", planePoints[0].Y), cereal::make_nvp("p0z", planePoints[0].Z),
           cereal::make_nvp("p1x", planePoints[1].X), cereal::make_nvp("p1y", planePoints[1].Y), cereal::make_nvp("p1z", planePoints[1].Z),
           cereal::make_nvp("p2x", planePoints[2].X), cereal::make_nvp("p2y", planePoints[2].Y), cereal::make_nvp("p2z", planePoints[2].Z),
           CEREAL_NVP(materialName),
           CEREAL_NVP(shaderName),
           cereal::make_nvp("uax", uAxis.X), cereal::make_nvp("uay", uAxis.Y), cereal::make_nvp("uaz", uAxis.Z),
           cereal::make_nvp("vax", vAxis.X), cereal::make_nvp("vay", vAxis.Y), cereal::make_nvp("vaz", vAxis.Z),
           CEREAL_NVP(shiftU), CEREAL_NVP(shiftV),
           CEREAL_NVP(scaleU), CEREAL_NVP(scaleV),
           CEREAL_NVP(rotationDeg),
           CEREAL_NVP(flags));
    }

    template<class Archive>
    void load(Archive& ar)
    {
        ar(cereal::make_nvp("p0x", planePoints[0].X), cereal::make_nvp("p0y", planePoints[0].Y), cereal::make_nvp("p0z", planePoints[0].Z),
           cereal::make_nvp("p1x", planePoints[1].X), cereal::make_nvp("p1y", planePoints[1].Y), cereal::make_nvp("p1z", planePoints[1].Z),
           cereal::make_nvp("p2x", planePoints[2].X), cereal::make_nvp("p2y", planePoints[2].Y), cereal::make_nvp("p2z", planePoints[2].Z),
           CEREAL_NVP(materialName),
           CEREAL_NVP(shaderName),
           cereal::make_nvp("uax", uAxis.X), cereal::make_nvp("uay", uAxis.Y), cereal::make_nvp("uaz", uAxis.Z),
           cereal::make_nvp("vax", vAxis.X), cereal::make_nvp("vay", vAxis.Y), cereal::make_nvp("vaz", vAxis.Z),
           CEREAL_NVP(shiftU), CEREAL_NVP(shiftV),
           CEREAL_NVP(scaleU), CEREAL_NVP(scaleV),
           CEREAL_NVP(rotationDeg),
           CEREAL_NVP(flags));
    }
};

struct Brush
{
    // ---- persistent ----
    uint32_t    id = 0;                 // stable, assigned by BrushManager, never reused
    std::string name;                   // hierarchy display, defaults to "Brush <id>"
    std::vector<BrushFace> faces;       // 4..MAX_FACES, validated by BrushGeometry
    irr::u8     solidClass = SOLID_WORLD;
    bool        castShadows = true;
    bool        receivesLightmap = true;
    irr::u32    contentFlags = 0;               // BrushContentFlags; 0 = normal structural brush
    std::string receiver;                       // trigger targets: CSV entity names
                                                // (LogicComponent::receiver convention, empty = unset)
    std::string owner;                          // SOLID_ENTITY only: name of the mover entity whose
                                                // mesh this brush compiles into; empty for world brushes

    // ---- derived (never serialized) ----
    std::vector<irr::core::vector3df> verts;    // welded shared vertex pool
    irr::core::aabbox3df bounds;
    irr::s64    chunkKey = -1;                  // packed cell coords of owning chunk
    bool        geometryValid = false;

    // Runtime trigger state (per play session — brushes are recreated on every
    // scene import, so entering editor-play resets these).
    bool triggerInside = false;                 // player was inside last frame (edge detect)
    bool triggerFired  = false;                 // CONTENT_TRIGGER_ONCE latch

    bool isToolBrush() const { return contentFlags != 0; }
    irr::u32 clipMask() const { return contentFlags & CONTENT_CLIP_MASK; }
    bool isMoverBrush() const { return solidClass == SOLID_ENTITY; }

    template<class Archive>
    void save(Archive& ar) const
    {
        ar(CEREAL_NVP(id),
           CEREAL_NVP(name),
           cereal::make_nvp("faceCount", static_cast<uint32_t>(faces.size())));
        for (const auto& f : faces)
            ar(cereal::make_nvp("face", f));
        ar(CEREAL_NVP(solidClass),
           CEREAL_NVP(castShadows),
           CEREAL_NVP(receivesLightmap),
           CEREAL_NVP(contentFlags),
           CEREAL_NVP(receiver),
           CEREAL_NVP(owner));
    }

    // Called manually by BrushManager::deserialize with the file-level schema
    // version (not through cereal's NVP path — versioning needs the argument).
    // version 0 files predate contentFlags/receiver; defaults hold.
    template<class Archive>
    void load(Archive& ar, uint32_t version)
    {
        uint32_t faceCount = 0;
        ar(CEREAL_NVP(id),
           CEREAL_NVP(name),
           cereal::make_nvp("faceCount", faceCount));
        faces.resize(faceCount);
        for (uint32_t i = 0; i < faceCount; i++)
            ar(cereal::make_nvp("face", faces[i]));
        ar(CEREAL_NVP(solidClass),
           CEREAL_NVP(castShadows),
           CEREAL_NVP(receivesLightmap));
        if (version >= 1)
            ar(CEREAL_NVP(contentFlags),
               CEREAL_NVP(receiver));
        if (version >= 2)
            ar(CEREAL_NVP(owner));
    }
};
