#version 330 compatibility

// Per-frame constants — std140 block filled once per frame by RenderManager
// (updatePerFrameUBO) and bound to binding point 0 by the fork patch in
// COpenGLSLMaterialRenderer (see Include/irrlicht/PATCHES.md). Member names
// match the old per-draw uniforms; layout must mirror struct PerFrameData in
// RenderManager.cpp. fTime is engine time in MILLISECONDS; uTime is seconds.
layout(std140) uniform PerFrame
{
    vec3  uAmbientColor;  float uHasShadow;
    vec3  uFogColor;      float uFogDensity;
    vec3  uCamRight;      float uFogStart;
    vec3  uCamUp;         float uHasEnvMap;
    vec3  uCamForward;    float uShadowBias;
    vec4  uClusterParams; // (tileW_px, tileH_px, sliceScale, sliceBias)
    float fTime;          float uTime;  float uUseClusters;  float uPrepassValid;
    mat4  uInvView;       // main camera view inverse — world-pos reconstruction
    mat4  uShadowMat[4];  // lightProj*lightView per shadow atlas slot
    vec4  uShadowRect[4]; // xy = atlas offset, z = scale, w = 1 if slot active
    vec4  uFogVolParams;  // x = active fog-volume count, y = feather distance
    vec4  uFogVolMin[8];  // xyz = AABB min, w = density
    vec4  uFogVolMax[8];  // xyz = AABB max, w = start distance
    vec4  uFogVolColor[8];// rgb = color, w = reserved
};

// ---------------------------------------------------------------------------
// Localized fog: integrate fog along the camera->fragment ray.  The scene
// default fog (uFogColor/uFogDensity/uFogStart) applies over the ray portion
// outside every fog volume; each CONTENT_FOG AABB overrides density+color for
// the segment inside it, softened by a feather at the faces.  Colour is an
// optical-depth-weighted average (ordering-free) — an approximation of true
// front-to-back compositing that reads correctly for the target cases.
// ---------------------------------------------------------------------------
vec3 applyLocalFog(vec3 color, vec3 viewPos)
{
    vec3  camWS    = uInvView[3].xyz;
    vec3  fragWS   = (uInvView * vec4(viewPos, 1.0)).xyz;
    vec3  ray      = fragWS - camWS;
    float fragDist = length(ray);
    if (fragDist < 1e-4)
        return color;
    vec3 dir = ray / fragDist;

    float feather = max(uFogVolParams.y, 1e-3);
    int   count   = int(uFogVolParams.x + 0.5);

    float tau      = 0.0;        // total optical depth along the ray
    vec3  colNum   = vec3(0.0);  // sum of (segment colour * segment optical depth)
    float inLenSum = 0.0;        // total path length inside any volume

    for (int i = 0; i < 8; ++i)
    {
        if (i >= count)
            break;

        vec3 bmin = uFogVolMin[i].xyz;
        vec3 bmax = uFogVolMax[i].xyz;

        // Ray-AABB slab test in world space, clamped to [0, fragDist].
        // Nudge exact-zero ray axes off zero first: 1.0/0.0 = inf, and inf on a
        // face-aligned axis gives 0*inf = NaN, which whites out the fragment.
        vec3 dsafe  = dir + vec3(equal(dir, vec3(0.0))) * 1e-6;
        vec3 invD   = 1.0 / dsafe;
        vec3 t0     = (bmin - camWS) * invD;
        vec3 t1     = (bmax - camWS) * invD;
        vec3 tsmall = min(t0, t1);
        vec3 tbig   = max(t0, t1);
        float tNear = max(max(tsmall.x, tsmall.y), tsmall.z);
        float tFar  = min(min(tbig.x, tbig.y), tbig.z);
        tNear = max(tNear, 0.0);
        tNear = max(tNear, uFogVolMax[i].w);   // per-volume start distance from camera
        tFar  = min(tFar, fragDist);

        float inLen = max(tFar - tNear, 0.0);
        if (inLen <= 0.0)
            continue;

        // Feather: ramp the segment's contribution up over the first `feather`
        // world units so grazing/edge rays fade in instead of popping.
        float r    = clamp(inLen / feather, 0.0, 1.0);
        float soft = r * r * (3.0 - 2.0 * r);          // smoothstep
        float tauI = uFogVolMin[i].w * inLen * soft;

        tau      += tauI;
        colNum   += tauI * uFogVolColor[i].rgb;
        inLenSum += inLen;
    }

    // Scene-default fog over the ray portion not covered by any volume.
    float outDist = max((fragDist - inLenSum) - uFogStart, 0.0);
    float tauDef  = uFogDensity * outDist;
    tau    += tauDef;
    colNum += tauDef * uFogColor;

    if (!(tau > 1e-5))   // also catches NaN (any comparison with NaN is false)
        return color;

    float fogFactor = clamp(1.0 - exp(-tau), 0.0, 1.0);
    return mix(color, colNum / tau, fogFactor);
}

// Hair Fragment Shader — Kajiya-Kay anisotropic specular
//
// A fork of phong_perpixel.frag: fog, clustered light fetch, shadow PCF and the
// derivative cotangent frame are identical, only the BRDF differs. Assigned per
// mesh BUFFER through MeshComponent::bufferShaderOverrides, never node-wide.
//
// GENERATED by Tools/assemble_character_shaders.py from phong_perpixel.frag plus
// hair_main.glsl. Edit those, not this file.
//
// MaterialTypeParams, pushed as named uniforms by HairShaderCallback (0 = default):
//   [0] roughness      (default 0.35) — see the uHairRoughness note in main()
//   [1] spec strength  (default 1.0)
//   [2] strand axis    (0 = strand runs along V, >= 0.5 = along U)
//   [3] alpha cutoff   (default 0.33)
//
// Registered over EMT_TRANSPARENT_ALPHA_CHANNEL_REF, so hair stays in the SOLID
// pass with depth writes — no sorting, no second pass.

#define MAX_LIGHTS 8
#define PI 3.14159265358979323846

varying vec3 vViewPos;
varying vec3 vViewNormal;
varying vec2 vTexCoord;
varying vec2 vLightmapUV;

uniform sampler2D tDiffuse;
uniform sampler2D tLightmap;
uniform float     uHasLightmap; // 1.0 if a baked lightmap texture is bound, else 0.0

uniform sampler2D tShadowMap;   // unit 11 — 4096 shadow ATLAS, four 2048 quadrants (R = depth)

varying vec4 vShadowClip[4];    // light clip-space coords per atlas slot (pre-divide)

// Lights in VIEW SPACE
uniform vec3  uLightPos[MAX_LIGHTS];
uniform vec4  uLightColor[MAX_LIGHTS];
uniform float uLightRadius[MAX_LIGHTS];
uniform float uLightCount;

// Spotlight cone data (only meaningful when uLightIsSpot[i] > 0.5)
uniform vec3  uLightDir[MAX_LIGHTS];      // view-space direction the spot is pointing
uniform float uLightIsSpot[MAX_LIGHTS];   // 1.0 = spotlight, 0.0 = point light
uniform float uLightCosOuter[MAX_LIGHTS]; // cos(outerCone half-angle) — hard cutoff
uniform float uLightCosInner[MAX_LIGHTS]; // cos(innerCone half-angle) — full brightness

// Clustered lighting (ClusteredLightManager). When uUseClusters > 0.5, per-light
// data comes from texelFetch textures on units 8-10 and the arrays above are
// unused. Grid layout constants must match ClusteredLightManager (16x8x24 grid,
// 4 texels per light, 256-wide index texture).
uniform sampler2D tLightData;     // unit 8: t0=pos+radius, t1=color+cosInner, t2=dir+cosOuter(-2=point)
uniform sampler2D tClusterGrid;   // unit 9: (offset, count) per froxel
uniform sampler2D tLightIndices;  // unit 10: flat light index list


// Hair shading params — MaterialTypeParams[0..3], pushed by HairShaderCallback.
uniform float uHairRoughness;
uniform float uSpecStrength;
uniform float uStrandAxis;    // 0 = strand along V (default), >= 0.5 = along U
uniform float uAlphaCutoff;   // core pass only; the fringe pass uses ~0.02
uniform float uBlendPass;     // 0 = alpha-tested core, 1 = blended fringe
uniform float uCoreCutoff;    // console r_haircutoff override; 0 = use material
uniform float uFringeGain;    // console r_hairgain; multiplies the fringe's alpha
uniform float uCoreOff;       // console r_haircoreoff; 1 = core discards all

// Flat-colour debug switch (console r_charshaderdebug) — proves whether this
// shader is bound before anyone starts tuning its parameters.
uniform float uDebugTint;

// PBR material params (mapped from SMaterial in C++)
//   uRoughness = 1 - sqrt(Shininess/128)   -- 0=mirror, 1=matte
//   uMetallic  = SpecularColor.alpha/255    -- 0=plastic, 1=metal
uniform float uRoughness;
uniform float uMetallic;



// Environment map (equirectangular) for ambient specular reflections
uniform sampler2D tEnvMap;
// Camera world-space basis vectors — used to convert the view-space reflection
// vector to world space without any matrix convention ambiguity.
// In OpenGL view space: X+=right, Y+=up, Z+=out-of-screen (-forward).

// PBR texture maps — slots 4-7 (each optional; uHas* gates the sample)
uniform sampler2D tNormalMap;
uniform float     uHasNormalMap;
uniform sampler2D tRoughnessMap;
uniform float     uHasRoughnessMap;
uniform sampler2D tMetallicMap;
uniform float     uHasMetallicMap;
uniform float     uHasORM;       // 1.0 when slots 5/6 share one packed ORM texture (R=AO, G=rough, B=metal)
uniform sampler2D tEmissionMap;
uniform float     uHasEmissionMap;

// ---------------------------------------------------------------------------
// GGX / Cook-Torrance helpers
// ---------------------------------------------------------------------------
float D_GGX(float NdotH, float roughness)
{
    float a  = roughness * roughness;
    float a2 = a * a;
    float d  = (NdotH * NdotH) * (a2 - 1.0) + 1.0;
    return a2 / (PI * d * d);
}

float G_SmithSchlick(float NdotV, float NdotL, float roughness)
{
    float k  = (roughness + 1.0) * (roughness + 1.0) / 8.0;
    float GV = NdotV / (NdotV * (1.0 - k) + k);
    float GL = NdotL / (NdotL * (1.0 - k) + k);
    return GV * GL;
}

vec3 F_Schlick(float VdotH, vec3 F0)
{
    return F0 + (1.0 - F0) * pow(clamp(1.0 - VdotH, 0.0, 1.0), 5.0);
}

// Fresnel for ambient/IBL, damped by roughness. Plain F_Schlick drives every
// surface to fully reflective at grazing angles, so a rough dielectric (skin,
// cloth) picks up the same bright env rim as polished metal — the "everything
// is coated in oil" look. Rough surfaces scatter that grazing energy instead.
vec3 F_SchlickRoughness(float NdotV, vec3 F0, float roughness)
{
    return F0 + (max(vec3(1.0 - roughness), F0) - F0)
                * pow(clamp(1.0 - NdotV, 0.0, 1.0), 5.0);
}

// 3x3 PCF against one shadow atlas quadrant. clip = light clip-space coords
// (pre-divide — dividing in the vertex shader would double-divide during
// varying interpolation); rect = (atlas offset.xy, scale, active). Returns
// light visibility: 1.0 = lit, 0.3 = fully shadowed (0.7 max darkness so
// ambient/baked light still reads inside shadows).
float shadowFactorPCF(vec4 clip, vec4 rect)
{
    vec3 sc = clip.xyz / clip.w;
    sc = sc * 0.5 + 0.5;
    if (sc.x < 0.0 || sc.x > 1.0 || sc.y < 0.0 || sc.y > 1.0 || sc.z < 0.0 || sc.z > 1.0)
        return 1.0;

    // Slope-scale bias: the constant term covers precision noise; the
    // derivative term grows the bias on surfaces at shallow angles to the
    // light, eliminating triangular acne without adding Peter-Panning.
    float slope = length(vec2(dFdx(sc.z), dFdy(sc.z)));
    float bias  = uShadowBias + slope * 3.0;

    // Clamp taps inside the quadrant (one-texel margin) so PCF never bleeds
    // into a neighboring light's map.
    float texel = 1.0 / 4096.0;
    vec2  base  = rect.xy + sc.xy * rect.z;
    vec2  lo    = rect.xy + vec2(texel);
    vec2  hi    = rect.xy + vec2(rect.z - texel);

    float shadowSum = 0.0;
    for (int sx = -1; sx <= 1; ++sx)
        for (int sy = -1; sy <= 1; ++sy)
        {
            vec2 auv = clamp(base + vec2(sx, sy) * texel, lo, hi);
            shadowSum += (sc.z - bias > texture2D(tShadowMap, auv).r) ? 1.0 : 0.0;
        }
    return 1.0 - (shadowSum / 9.0) * 0.7;
}

// ---------------------------------------------------------------------------
// Kajiya-Kay helpers
// ---------------------------------------------------------------------------

// Tilt the strand tangent toward or away from the surface normal. The two
// specular lobes are the SAME tangent shifted by different amounts — that
// offset between them is what reads as a highlight band travelling along the
// hair rather than sitting on it like a plastic sheen.
vec3 shiftTangent(vec3 T, vec3 N, float shift)
{
    return normalize(T + shift * N);
}

// Anisotropic specular along a strand: Kajiya-Kay's sin(T,H) lobe.
// dirAtten kills the lobe on the side of the strand facing away from the light,
// which plain pow(sinTH) does not do and which otherwise haloes backlit hair.
float strandSpecular(vec3 T, vec3 V, vec3 L, float exponent)
{
    vec3  H     = normalize(L + V);
    float dotTH = dot(T, H);
    float sinTH = sqrt(max(1.0 - dotTH * dotTH, 0.0));
    float dirAtten = smoothstep(-1.0, 0.0, dotTH);
    return dirAtten * pow(sinTH, exponent);
}

// ---------------------------------------------------------------------------
void main()
{
    // No UV animation on hair: MaterialTypeParams[0..3] carry this shader's own
    // tuning, so the base callback's tiling/scroll uniforms are not declared.
    vec2 animUV = vTexCoord;

    vec4 texColor = texture2D(tDiffuse, animUV);

    // Cut out FIRST — everything below is wasted work on a discarded fragment.
    //
    // This shader runs TWICE over the same buffers:
    //   uBlendPass == 0 — the CORE. Alpha-tested at uAlphaCutoff, depth written,
    //     drawn in the solid pass. Writes alpha 1.0 so survivors clear the
    //     fixed-function GL_GREATER 0.5 test this material type installs.
    //   uBlendPass == 1 — the FRINGE. Everything above a near-zero threshold,
    //     alpha-blended with depth test but no depth write, drawn afterwards by
    //     RenderManager::drawHairBlendPass(). Its depth func is LESS, so the
    //     core's own texels fail the test and are not blended over twice.
    // One pass alone cannot do this: a cut-out throws away the soft gradient
    // that is three quarters of a hair texture, and pure blending has no depth
    // order to sort by.
    // uCoreCutoff (console r_haircutoff) overrides the material's own value so
    // the threshold can be dialled at runtime; 0 means "use the material".
    float coreCutoff = (uCoreCutoff > 0.0) ? uCoreCutoff : uAlphaCutoff;
    float cutoff = (uBlendPass > 0.5) ? 0.02 : coreCutoff;
    if (texColor.a < cutoff)
        discard;

    // r_haircoreoff: kill the core outright so only the blended fringe reaches
    // the screen. Overlapping cards and depth rejection can both hide the fringe
    // behind the core; with the core gone, what is left is exactly what the
    // fringe pass contributes.
    if (uCoreOff > 0.5 && uBlendPass < 0.5)
        discard;

    vec3 albedo = pow(texColor.rgb, vec3(2.2)); // sRGB -> linear

    vec3 N = normalize(vViewNormal);
    vec3 V = normalize(-vViewPos);

    // Derivative cotangent frame — T runs along +U, B along +V, both in view
    // space. Hair cards are authored with the strand down one UV axis, so one of
    // these IS the strand direction; which one is per asset (uStrandAxis).
    // Scale-invariant form, same as phong_perpixel: see the long note there
    // about why dividing by the UV determinant silently drops detail up close.
    vec3  dp1  = dFdx(vViewPos);
    vec3  dp2  = dFdy(vViewPos);
    vec2  duv1 = dFdx(animUV);
    vec2  duv2 = dFdy(animUV);
    vec3 dp2perp = cross(dp2, N);
    vec3 dp1perp = cross(N, dp1);
    vec3 Traw = dp2perp * duv1.x + dp1perp * duv2.x;
    vec3 Braw = dp2perp * duv1.y + dp1perp * duv2.y;

    vec3 Tn = vec3(1.0, 0.0, 0.0);
    vec3 Bn = vec3(0.0, 1.0, 0.0);
    float maxSq = max(dot(Traw, Traw), dot(Braw, Braw));
    if (maxSq > 0.0)
    {
        float invmax = inversesqrt(maxSq);
        Tn = Traw * invmax;
        Bn = Braw * invmax;
        if (uHasNormalMap > 0.5)
            N = normalize(mat3(Tn, Bn, N)
                          * (texture2D(tNormalMap, animUV).rgb * 2.0 - 1.0));
    }

    vec3 strand = normalize(uStrandAxis >= 0.5 ? Tn : Bn);

    // No procedural jitter on the lobe shift. Two attempts at one both made the
    // hair worse: hashing the raw UV gives a fresh random number at every
    // FRAGMENT, which is white noise that sparkles and crawls under camera
    // motion; quantising that hash to strand columns turns the noise into
    // regular vertical stripes, which is just as wrong and more obvious.
    //
    // The variation belongs to the asset. Hair_Normal already perturbs N per
    // strand, and both lobes are shifted along N, so every strand gets its own
    // highlight position for free and it is consistent frame to frame.
    const float jitter = 0.0;

    float NdotV = max(dot(N, V), 0.0001);

    // Roughness comes from uHairRoughness, NOT from the ORM texture: a glTF hair
    // material with no metallicRoughness map gets a 1x1 ORM holding the format's
    // DEFAULT roughness of 1.0, and every specular path in this engine is gated
    // on roughness < 0.99. Reading the map here would switch this entire shader
    // off and leave flat Lambert albedo — which is exactly the bug this shader
    // exists to fix.
    float roughness = clamp(uHairRoughness, 0.03, 0.95);
    float expPrimary   = mix(160.0, 24.0, roughness);
    float expSecondary = expPrimary * 0.25;

    // Specular antialiasing (Toksvig in spirit, derivatives instead of a mip
    // chain). A pixel covering many strands sees a normal that swings wildly
    // inside its own footprint; evaluating a 100+ exponent lobe against one
    // point sample of that normal is what makes hair sparkle and crawl. Where
    // the normal varies fast on screen, widen the lobe to roughly the spread the
    // pixel actually covers, and damp its intensity to match — a wide lobe at
    // full strength would just smear the sparkle into a glare.
    float normalVar = clamp(length(fwidth(N)) * 1.5, 0.0, 1.0);
    expPrimary   = mix(expPrimary,   10.0, normalVar);
    expSecondary = mix(expSecondary,  5.0, normalVar);
    float specAA = mix(1.0, 0.45, normalVar);

    // Dielectric. Hair is never metal, so no metallic lookup and no F0 tint.
    vec3 F0 = vec3(0.05);

    vec3 diffuseAccum  = vec3(0.0);
    vec3 specularAccum = vec3(0.0);

    int lightOffset = 0;
    int lightNum    = int(uLightCount);
    if (uUseClusters > 0.5)
    {
        ivec2 tile  = clamp(ivec2(gl_FragCoord.xy / uClusterParams.xy), ivec2(0), ivec2(15, 7));
        int   slice = clamp(int(floor(log2(max(vViewPos.z, 0.01)) * uClusterParams.z + uClusterParams.w)), 0, 23);
        vec2  oc    = texelFetch(tClusterGrid, ivec2(tile.x + tile.y * 16, slice), 0).xy;
        lightOffset = int(oc.x);
        lightNum    = int(oc.y);
    }

    for (int n = 0; n < lightNum; n++)
    {
        vec3  lightPos;
        vec3  lightColor;
        float lightRadius;
        vec3  spotDir;
        bool  isSpot;
        float cosOuter, cosInner;
        int   shadowSlot;

        if (uUseClusters > 0.5)
        {
            int  fi = lightOffset + n;
            int  li = int(texelFetch(tLightIndices, ivec2(fi & 255, fi >> 8), 0).x);
            vec4 t0 = texelFetch(tLightData, ivec2(li * 4 + 0, 0), 0);
            vec4 t1 = texelFetch(tLightData, ivec2(li * 4 + 1, 0), 0);
            vec4 t2 = texelFetch(tLightData, ivec2(li * 4 + 2, 0), 0);
            vec4 t3 = texelFetch(tLightData, ivec2(li * 4 + 3, 0), 0);
            lightPos    = t0.xyz;  lightRadius = t0.w;
            lightColor  = t1.xyz;  cosInner    = t1.w;
            spotDir     = t2.xyz;  cosOuter    = t2.w;
            isSpot      = (cosOuter > -1.5);   // -2 marks a point light
            shadowSlot  = int(t3.x);           // -1 = casts no shadow
        }
        else
        {
            lightPos    = uLightPos[n];
            lightColor  = uLightColor[n].rgb;
            lightRadius = uLightRadius[n];
            spotDir     = uLightDir[n];
            isSpot      = uLightIsSpot[n] > 0.5;
            cosOuter    = uLightCosOuter[n];
            cosInner    = uLightCosInner[n];
            shadowSlot  = -1;
        }

        vec3  toLight = lightPos - vViewPos;
        float dist    = length(toLight);
        vec3  L       = toLight / dist;

        float atten = clamp(1.0 - (dist * dist) / (lightRadius * lightRadius), 0.0, 1.0);
        if (atten <= 0.0) continue;

        if (isSpot)
        {
            float cosAngle = dot(-L, spotDir);
            atten *= smoothstep(cosOuter, cosInner, cosAngle);
            if (atten <= 0.0) continue;
        }

        float NdotL = dot(N, L);

        // A strand is a cylinder: its shaded half never goes fully black, and a
        // hard max(NdotL, 0) puts a visible edge straight across the cards.
        float wrapped = clamp((NdotL + 0.3) / 1.3, 0.0, 1.0);

        // Light passing THROUGH the hair from behind. This is most of what makes
        // backlit hair read as hair rather than as a dark silhouette.
        float back = pow(clamp(dot(V, -L), 0.0, 1.0), 4.0) * 0.6;

        vec3 thisDiffuse  = lightColor * (wrapped + back) * atten;
        vec3 thisSpecular = vec3(0.0);

        {
            vec3 t1 = shiftTangent(strand, N, -0.08 + jitter);
            vec3 t2 = shiftTangent(strand, N,  0.12 + jitter);

            float s1 = strandSpecular(t1, V, L, expPrimary);
            float s2 = strandSpecular(t2, V, L, expSecondary);

            // The primary lobe reflects off the cuticle and stays UNCOLOURED;
            // the secondary has travelled through the strand and comes back
            // tinted by the hair's own colour. The tinted one is what sells the
            // material, so it carries the larger weight.
            //
            // NOT multiplied by Fresnel. A dielectric F0 is 0.05, so folding
            // F_Schlick in here scaled the whole highlight to ~3% of the light
            // colour and the shader looked exactly like the Lambert it replaced.
            // Kajiya-Kay lobes are an empirical fit, not a microfacet BRDF with
            // an energy budget to respect — the weights below ARE the strength,
            // and uSpecStrength is the knob on top.
            vec3 spec = (vec3(s1) * 0.20 + albedo * s2 * 0.50) * specAA;

            // Half-Lambert rather than NdotL: clamping to zero here would cut the
            // grazing highlight that runs along the silhouette of the head.
            thisSpecular = spec * lightColor * clamp(NdotL * 0.5 + 0.5, 0.0, 1.0)
                         * atten * uSpecStrength;
        }

        if (shadowSlot >= 0 && uShadowRect[shadowSlot].w > 0.5)
        {
            float sf = shadowFactorPCF(vShadowClip[shadowSlot], uShadowRect[shadowSlot]);
            thisDiffuse  *= sf;
            thisSpecular *= sf;
        }

        diffuseAccum  += thisDiffuse;
        specularAccum += thisSpecular;
    }

    // Hair is dense enough that ambient light does not reach the inner strands.
    // The asset carries no AO for it (a hair material typically has no ORM at
    // all), so this stands in for one — without it the whole head lifts to a
    // flat wash under scene ambient and every lobe above is lost in it.
    const float hairAmbientOcclusion = 0.6;
    vec3 bakedLight = ((uHasLightmap > 0.5)
        ? pow(texture2D(tLightmap, vLightmapUV).rgb, vec3(2.2)) + uAmbientColor
        : uAmbientColor) * hairAmbientOcclusion;

    if (uHasEnvMap > 0.5)
    {
        vec3 R_view  = reflect(-V, N);
        vec3 R_world = mat3(uCamRight, uCamUp, uCamForward) * R_view;
        vec2 envUV = vec2(
            atan(R_world.x, R_world.z) / (2.0 * PI),
            asin(clamp(-R_world.y, -1.0, 1.0)) / PI + 0.5
        );
        vec3 envSample = pow(textureLod(tEnvMap, envUV, roughness * 7.0).rgb, vec3(2.2));
        vec3 envF      = F_SchlickRoughness(NdotV, F0, roughness);
        float ambientLum = dot(uAmbientColor, vec3(0.2126, 0.7152, 0.0722));
        // Tinted by albedo and damped hard: an untinted mirror reflection on
        // hair is the "wet plastic wig" look.
        specularAccum += envSample * envF * albedo * (1.0 - roughness) * 1.5
                       * uSpecStrength * hairAmbientOcclusion
                       * smoothstep(0.0, 0.05, ambientLum);
    }

    vec3 color = albedo * max(bakedLight, diffuseAccum) + specularAccum;

    // r_charshaderdebug: MAGENTA for the alpha-tested core, CYAN for the blended
    // fringe. The two failure modes look identical from outside — a fringe pass
    // that never runs and a fringe pass that runs but contributes nothing — and
    // this separates them: no cyan anywhere means drawHairBlendPass() is not
    // reaching these buffers.
    if (uDebugTint > 0.5)
        color = (uBlendPass > 0.5) ? vec3(0.0, 1.0, 1.0) : vec3(1.0, 0.0, 1.0);

    // Core pass: alpha 1.0, so every survivor of the cut-out clears the
    // fixed-function test. Fringe pass: the texture's own coverage, which is the
    // whole point of drawing it a second time.
    // Fringe coverage. uFringeGain (console r_hairgain) thickens the wisps:
    // the texture's own alpha is what the artist authored for a renderer that
    // composites hair differently, and 1.0 of it can read as too thin here.
    float outAlpha = 1.0;
    if (uBlendPass > 0.5)
        outAlpha = clamp(texColor.a * max(uFringeGain, 0.001), 0.0, 1.0);

    // Under the debug tint the fringe is forced fully opaque. A pass that is
    // drawing faintly and a pass that is being depth-rejected look the same at
    // low alpha; at alpha 1.0 every pixel the fringe actually reaches turns
    // solid cyan, which separates them at a glance.
    if (uDebugTint > 0.5 && uBlendPass > 0.5)
        outAlpha = 1.0;

    gl_FragColor = vec4(applyLocalFog(color, vViewPos), outAlpha);
}
