#version 330 compatibility

// Per-frame constants — std140 block filled once per frame by RenderManager
// (updatePerFrameUBO) and bound to binding point 0 by the fork patch in
// COpenGLSLMaterialRenderer (see Include/irrlicht/PATCHES.md). Member names
// match the old per-draw uniforms; layout must mirror struct PerFrameData in
// RenderManager.cpp. fTime is engine time in MILLISECONDS; uTime is seconds.
layout(std140) uniform PerFrame
{
    vec3  uAmbientColor;  float uHasShadow;
    vec3  uFogColor;      float uFogDensity;
    vec3  uCamRight;      float uFogStart;
    vec3  uCamUp;         float uHasEnvMap;
    vec3  uCamForward;    float uShadowBias;
    vec4  uClusterParams; // (tileW_px, tileH_px, sliceScale, sliceBias)
    float fTime;          float uTime;  float uUseClusters;  float uPrepassValid;
    mat4  uInvView;       // main camera view inverse — world-pos reconstruction
    mat4  uShadowMat[4];  // lightProj*lightView per shadow atlas slot
    vec4  uShadowRect[4]; // xy = atlas offset, z = scale, w = 1 if slot active
    vec4  uFogVolParams;  // x = active fog-volume count, y = feather distance
    vec4  uFogVolMin[8];  // xyz = AABB min, w = density
    vec4  uFogVolMax[8];  // xyz = AABB max, w = start distance
    vec4  uFogVolColor[8];// rgb = color, w = reserved
};

// ---------------------------------------------------------------------------
// Localized fog: integrate fog along the camera->fragment ray.  The scene
// default fog (uFogColor/uFogDensity/uFogStart) applies over the ray portion
// outside every fog volume; each CONTENT_FOG AABB overrides density+color for
// the segment inside it, softened by a feather at the faces.  Colour is an
// optical-depth-weighted average (ordering-free) — an approximation of true
// front-to-back compositing that reads correctly for the target cases.
// ---------------------------------------------------------------------------
vec3 applyLocalFog(vec3 color, vec3 viewPos)
{
    vec3  camWS    = uInvView[3].xyz;
    vec3  fragWS   = (uInvView * vec4(viewPos, 1.0)).xyz;
    vec3  ray      = fragWS - camWS;
    float fragDist = length(ray);
    if (fragDist < 1e-4)
        return color;
    vec3 dir = ray / fragDist;

    float feather = max(uFogVolParams.y, 1e-3);
    int   count   = int(uFogVolParams.x + 0.5);

    float tau      = 0.0;        // total optical depth along the ray
    vec3  colNum   = vec3(0.0);  // sum of (segment colour * segment optical depth)
    float inLenSum = 0.0;        // total path length inside any volume

    for (int i = 0; i < 8; ++i)
    {
        if (i >= count)
            break;

        vec3 bmin = uFogVolMin[i].xyz;
        vec3 bmax = uFogVolMax[i].xyz;

        // Ray-AABB slab test in world space, clamped to [0, fragDist].
        // Nudge exact-zero ray axes off zero first: 1.0/0.0 = inf, and inf on a
        // face-aligned axis gives 0*inf = NaN, which whites out the fragment.
        vec3 dsafe  = dir + vec3(equal(dir, vec3(0.0))) * 1e-6;
        vec3 invD   = 1.0 / dsafe;
        vec3 t0     = (bmin - camWS) * invD;
        vec3 t1     = (bmax - camWS) * invD;
        vec3 tsmall = min(t0, t1);
        vec3 tbig   = max(t0, t1);
        float tNear = max(max(tsmall.x, tsmall.y), tsmall.z);
        float tFar  = min(min(tbig.x, tbig.y), tbig.z);
        tNear = max(tNear, 0.0);
        tNear = max(tNear, uFogVolMax[i].w);   // per-volume start distance from camera
        tFar  = min(tFar, fragDist);

        float inLen = max(tFar - tNear, 0.0);
        if (inLen <= 0.0)
            continue;

        // Feather: ramp the segment's contribution up over the first `feather`
        // world units so grazing/edge rays fade in instead of popping.
        float r    = clamp(inLen / feather, 0.0, 1.0);
        float soft = r * r * (3.0 - 2.0 * r);          // smoothstep
        float tauI = uFogVolMin[i].w * inLen * soft;

        tau      += tauI;
        colNum   += tauI * uFogVolColor[i].rgb;
        inLenSum += inLen;
    }

    // Scene-default fog over the ray portion not covered by any volume.
    float outDist = max((fragDist - inLenSum) - uFogStart, 0.0);
    float tauDef  = uFogDensity * outDist;
    tau    += tauDef;
    colNum += tauDef * uFogColor;

    if (!(tau > 1e-5))   // also catches NaN (any comparison with NaN is false)
        return color;

    float fogFactor = clamp(1.0 - exp(-tau), 0.0, 1.0);
    return mix(color, colNum / tau, fogFactor);
}

// Skin Fragment Shader — pre-integrated subsurface scattering + dual-lobe specular
//
// A fork of phong_perpixel.frag: fog, clustered light fetch, shadow PCF and the
// derivative cotangent frame are identical, only the BRDF differs. Assigned per
// mesh BUFFER through MeshComponent::bufferShaderOverrides, never node-wide.
//
// GENERATED by Tools/assemble_character_shaders.py from phong_perpixel.frag plus
// skin_main.glsl. Edit those, not this file.
//
// The scattering table is built by Tools/generate_skin_lut.py and bound to raw
// GL unit 13 once per frame by RenderManager::bindPerFrameTextures(). When it is
// missing, uHasSkinLUT is 0 and the shader degrades to plain Lambert diffuse.
//
// MaterialTypeParams, pushed as named uniforms by SkinShaderCallback (0 = default):
//   [0] subsurface strength (default 1.0) — 0 blends back to Lambert
//   [1] curvature scale     (default 0.2) — see SkinShaderCallback::OnSetConstants
//                              for the history (originally 4.0, then 1.0). The
//                              screen-space curvature estimate can't tell genuine
//                              tight curvature apart from a mesh seam, a hard
//                              normal break, or a near-silhouette angle, and on
//                              at least one asset (the paladin) it needed this
//                              much headroom to avoid a mesh-wide false-positive
//                              red terminator smear. Raise per-asset if an asset
//                              needs the effect stronger; think twice before
//                              raising the shared default back up
//   [2] spec strength       (default 1.0)
//   [3] transmission        (default 0.35)

#define MAX_LIGHTS 8
#define PI 3.14159265358979323846

varying vec3 vViewPos;
varying vec3 vViewNormal;
varying vec2 vTexCoord;
varying vec2 vLightmapUV;

uniform sampler2D tDiffuse;
uniform sampler2D tLightmap;
uniform float     uHasLightmap; // 1.0 if a baked lightmap texture is bound, else 0.0

uniform sampler2D tShadowMap;   // unit 11 — 4096 shadow ATLAS, four 2048 quadrants (R = depth)

varying vec4 vShadowClip[4];    // light clip-space coords per atlas slot (pre-divide)

// Lights in VIEW SPACE
uniform vec3  uLightPos[MAX_LIGHTS];
uniform vec4  uLightColor[MAX_LIGHTS];
uniform float uLightRadius[MAX_LIGHTS];
uniform float uLightCount;

// Spotlight cone data (only meaningful when uLightIsSpot[i] > 0.5)
uniform vec3  uLightDir[MAX_LIGHTS];      // view-space direction the spot is pointing
uniform float uLightIsSpot[MAX_LIGHTS];   // 1.0 = spotlight, 0.0 = point light
uniform float uLightCosOuter[MAX_LIGHTS]; // cos(outerCone half-angle) — hard cutoff
uniform float uLightCosInner[MAX_LIGHTS]; // cos(innerCone half-angle) — full brightness

// Clustered lighting (ClusteredLightManager). When uUseClusters > 0.5, per-light
// data comes from texelFetch textures on units 8-10 and the arrays above are
// unused. Grid layout constants must match ClusteredLightManager (16x8x24 grid,
// 4 texels per light, 256-wide index texture).
uniform sampler2D tLightData;     // unit 8: t0=pos+radius, t1=color+cosInner, t2=dir+cosOuter(-2=point)
uniform sampler2D tClusterGrid;   // unit 9: (offset, count) per froxel
uniform sampler2D tLightIndices;  // unit 10: flat light index list


// Skin shading params — MaterialTypeParams[0..3], pushed by SkinShaderCallback.
uniform float uSSSStrength;
uniform float uCurvatureScale;
uniform float uSpecStrength;
uniform float uTransStrength;

// Pre-integrated scattering LUT: x = NdotL * 0.5 + 0.5, y = curvature.
// Raw GL unit 13 (above Irrlicht's 8 material slots), so nothing rebinds it.
uniform sampler2D tSkinLUT;
uniform float     uHasSkinLUT;   // 0 when the LUT asset failed to load

// Flat-colour debug switch (console r_charshaderdebug) — proves whether this
// shader is bound before anyone starts tuning its parameters.
uniform float uDebugTint;

// PBR material params (mapped from SMaterial in C++)
//   uRoughness = 1 - sqrt(Shininess/128)   -- 0=mirror, 1=matte
//   uMetallic  = SpecularColor.alpha/255    -- 0=plastic, 1=metal
uniform float uRoughness;
uniform float uMetallic;



// Environment map (equirectangular) for ambient specular reflections
uniform sampler2D tEnvMap;
// Camera world-space basis vectors — used to convert the view-space reflection
// vector to world space without any matrix convention ambiguity.
// In OpenGL view space: X+=right, Y+=up, Z+=out-of-screen (-forward).

// PBR texture maps — slots 4-7 (each optional; uHas* gates the sample)
uniform sampler2D tNormalMap;
uniform float     uHasNormalMap;
uniform sampler2D tRoughnessMap;
uniform float     uHasRoughnessMap;
uniform sampler2D tMetallicMap;
uniform float     uHasMetallicMap;
uniform float     uHasORM;       // 1.0 when slots 5/6 share one packed ORM texture (R=AO, G=rough, B=metal)
uniform sampler2D tEmissionMap;
uniform float     uHasEmissionMap;

// ---------------------------------------------------------------------------
// GGX / Cook-Torrance helpers
// ---------------------------------------------------------------------------
float D_GGX(float NdotH, float roughness)
{
    float a  = roughness * roughness;
    float a2 = a * a;
    float d  = (NdotH * NdotH) * (a2 - 1.0) + 1.0;
    return a2 / (PI * d * d);
}

float G_SmithSchlick(float NdotV, float NdotL, float roughness)
{
    float k  = (roughness + 1.0) * (roughness + 1.0) / 8.0;
    float GV = NdotV / (NdotV * (1.0 - k) + k);
    float GL = NdotL / (NdotL * (1.0 - k) + k);
    return GV * GL;
}

vec3 F_Schlick(float VdotH, vec3 F0)
{
    return F0 + (1.0 - F0) * pow(clamp(1.0 - VdotH, 0.0, 1.0), 5.0);
}

// Fresnel for ambient/IBL, damped by roughness. Plain F_Schlick drives every
// surface to fully reflective at grazing angles, so a rough dielectric (skin,
// cloth) picks up the same bright env rim as polished metal — the "everything
// is coated in oil" look. Rough surfaces scatter that grazing energy instead.
vec3 F_SchlickRoughness(float NdotV, vec3 F0, float roughness)
{
    return F0 + (max(vec3(1.0 - roughness), F0) - F0)
                * pow(clamp(1.0 - NdotV, 0.0, 1.0), 5.0);
}

// 3x3 PCF against one shadow atlas quadrant. clip = light clip-space coords
// (pre-divide — dividing in the vertex shader would double-divide during
// varying interpolation); rect = (atlas offset.xy, scale, active). Returns
// light visibility: 1.0 = lit, 0.3 = fully shadowed (0.7 max darkness so
// ambient/baked light still reads inside shadows).
float shadowFactorPCF(vec4 clip, vec4 rect)
{
    vec3 sc = clip.xyz / clip.w;
    sc = sc * 0.5 + 0.5;
    if (sc.x < 0.0 || sc.x > 1.0 || sc.y < 0.0 || sc.y > 1.0 || sc.z < 0.0 || sc.z > 1.0)
        return 1.0;

    // Slope-scale bias: the constant term covers precision noise; the
    // derivative term grows the bias on surfaces at shallow angles to the
    // light, eliminating triangular acne without adding Peter-Panning.
    float slope = length(vec2(dFdx(sc.z), dFdy(sc.z)));
    float bias  = uShadowBias + slope * 3.0;

    // Clamp taps inside the quadrant (one-texel margin) so PCF never bleeds
    // into a neighboring light's map.
    float texel = 1.0 / 4096.0;
    vec2  base  = rect.xy + sc.xy * rect.z;
    vec2  lo    = rect.xy + vec2(texel);
    vec2  hi    = rect.xy + vec2(rect.z - texel);

    float shadowSum = 0.0;
    for (int sx = -1; sx <= 1; ++sx)
        for (int sy = -1; sy <= 1; ++sy)
        {
            vec2 auv = clamp(base + vec2(sx, sy) * texel, lo, hi);
            shadowSum += (sc.z - bias > texture2D(tShadowMap, auv).r) ? 1.0 : 0.0;
        }
    return 1.0 - (shadowSum / 9.0) * 0.7;
}

// Unit conversion for the scattering table. These three MUST match
// Tools/generate_skin_lut.py — the table is baked with them, so a mismatch
// silently reads the wrong row rather than failing.
//   WORLD_UNIT_MM : mm per engine world unit (the paladin is 2.383 units for
//                   a ~1.8 m human, so ~755)
//   RADIUS_MIN_MM : ring radius at LUT y = 1 (sharpest feature modelled)
//   RADIUS_MAX_MM : ring radius at LUT y = 0 (flat; that row is Lambert)
#define WORLD_UNIT_MM  755.0
#define RADIUS_MIN_MM  1.0
#define RADIUS_MAX_MM  200.0

// ---------------------------------------------------------------------------
void main()
{
    // No UV animation on skin: MaterialTypeParams[0..3] carry this shader's own
    // tuning, so the base callback's tiling/scroll uniforms are not declared.
    vec2 animUV = vTexCoord;

    vec4 texColor = texture2D(tDiffuse, animUV);
    vec3 albedo   = pow(texColor.rgb, vec3(2.2)); // sRGB -> linear

    vec3 N     = normalize(vViewNormal);
    vec3 Ngeom = N;   // keep the INTERPOLATED normal — curvature comes from it
    vec3 V     = normalize(-vViewPos);

    // Normal map — same derivative cotangent frame as phong_perpixel.
    if (uHasNormalMap > 0.5)
    {
        vec3  dp1  = dFdx(vViewPos);
        vec3  dp2  = dFdy(vViewPos);
        vec2  duv1 = dFdx(animUV);
        vec2  duv2 = dFdy(animUV);
        vec3 dp2perp = cross(dp2, N);
        vec3 dp1perp = cross(N, dp1);
        vec3 T = dp2perp * duv1.x + dp1perp * duv2.x;
        vec3 B = dp2perp * duv1.y + dp1perp * duv2.y;
        float maxSq = max(dot(T, T), dot(B, B));
        if (maxSq > 0.0)
        {
            float invmax = inversesqrt(maxSq);
            N = normalize(mat3(T * invmax, B * invmax, N)
                          * (texture2D(tNormalMap, animUV).rgb * 2.0 - 1.0));
        }
    }

    float NdotV = max(dot(N, V), 0.0001);

    // Surface curvature, from screen-space derivatives of the GEOMETRIC normal.
    // It must be Ngeom and not the mapped N: pore-level normal-map detail has
    // enormous local curvature and would drive the whole face to the scattered
    // end of the table.
    //
    // Curvature comes out in 1/world-unit; the table is indexed by ring RADIUS
    // in mm, on a logarithmic axis, because skin's diffusion length is a couple
    // of mm and a linear axis would spend most of its rows on surfaces too flat
    // to scatter at all. uCurvatureScale is the per-asset trim on top: 1.0 is
    // physically scaled (subtle on cheeks, strong on nose/ears/fingers, which is
    // how skin actually behaves), higher exaggerates it for a distant camera.
    float curvature = length(fwidth(Ngeom)) / max(length(fwidth(vViewPos)), 1e-5);
    float radiusMM  = WORLD_UNIT_MM / max(curvature * uCurvatureScale, 1e-4);
    float lutY = clamp(1.0 - log(radiusMM / RADIUS_MIN_MM) / log(RADIUS_MAX_MM / RADIUS_MIN_MM),
                       0.0, 1.0);

    // Screen-space curvature is a lie at a silhouette. The normal swings through
    // ninety degrees across two pixels, and the 2x2 derivative quad straddles
    // the edge of the model, so the estimate pins itself to the most-scattering
    // row of the table along every outline — which reads as a RED RIM around the
    // character, strongest when the light is behind them.
    //
    // The tell is the depth derivative: on a continuous surface it is a small
    // fraction of the view distance, and at an edge it jumps. Fade the whole
    // effect out there and let those pixels shade as plain skin.
    float depthGrad     = length(fwidth(vViewPos)) / max(length(vViewPos), 1e-3);
    float silhouetteFade = 1.0 - smoothstep(0.010, 0.045, depthGrad);

    // depthGrad only fires once a triangle edge actually straddles the model's
    // silhouette. A smooth, continuously curved patch viewed near edge-on (cheek
    // or jaw in three-quarter profile, not an outline pixel) drives the SAME
    // curvature blow-up without a depth discontinuity to trip on — and depthGrad's
    // threshold is a raw screen-space derivative, so it scales with camera
    // distance/FOV: the same grazing angle trips a weaker fade from farther away
    // (the same class of bug as the derivative TBN det guard — an absolute
    // epsilon on a quantity that isn't distance-invariant). NdotV against the
    // GEOMETRIC normal (pre normal-map, so it doesn't jitter with pore detail)
    // is angle-only and catches grazing views the depth test misses.
    float NdotVgeom = max(dot(Ngeom, V), 0.0);
    float grazeFade = smoothstep(0.05, 0.25, NdotVgeom);
    float edgeFade  = silhouetteFade * grazeFade;
    lutY *= edgeFade;

    // Roughness from the ORM's green channel, as everywhere else. Metallic is
    // NOT read: skin is a dielectric, and the alpha-of-SpecularColor path that
    // feeds uMetallic defaults to fully-metal on a raw scene node, which would
    // zero the diffuse and render the character black.
    float roughness = (uHasRoughnessMap > 0.5) ? texture2D(tRoughnessMap, animUV).g : uRoughness;
    float occlusion = (uHasORM > 0.5) ? texture2D(tRoughnessMap, animUV).r : 1.0;

    // Skin's index of refraction puts F0 at ~0.028, not the 0.04 default used
    // for generic dielectrics. The difference is small but it is the difference
    // between "damp" and "dry" on a face.
    vec3 F0 = vec3(0.028);

    vec3 diffuseAccum  = vec3(0.0);
    vec3 specularAccum = vec3(0.0);

    int lightOffset = 0;
    int lightNum    = int(uLightCount);
    if (uUseClusters > 0.5)
    {
        ivec2 tile  = clamp(ivec2(gl_FragCoord.xy / uClusterParams.xy), ivec2(0), ivec2(15, 7));
        int   slice = clamp(int(floor(log2(max(vViewPos.z, 0.01)) * uClusterParams.z + uClusterParams.w)), 0, 23);
        vec2  oc    = texelFetch(tClusterGrid, ivec2(tile.x + tile.y * 16, slice), 0).xy;
        lightOffset = int(oc.x);
        lightNum    = int(oc.y);
    }

    for (int n = 0; n < lightNum; n++)
    {
        vec3  lightPos;
        vec3  lightColor;
        float lightRadius;
        vec3  spotDir;
        bool  isSpot;
        float cosOuter, cosInner;
        int   shadowSlot;

        if (uUseClusters > 0.5)
        {
            int  fi = lightOffset + n;
            int  li = int(texelFetch(tLightIndices, ivec2(fi & 255, fi >> 8), 0).x);
            vec4 t0 = texelFetch(tLightData, ivec2(li * 4 + 0, 0), 0);
            vec4 t1 = texelFetch(tLightData, ivec2(li * 4 + 1, 0), 0);
            vec4 t2 = texelFetch(tLightData, ivec2(li * 4 + 2, 0), 0);
            vec4 t3 = texelFetch(tLightData, ivec2(li * 4 + 3, 0), 0);
            lightPos    = t0.xyz;  lightRadius = t0.w;
            lightColor  = t1.xyz;  cosInner    = t1.w;
            spotDir     = t2.xyz;  cosOuter    = t2.w;
            isSpot      = (cosOuter > -1.5);   // -2 marks a point light
            shadowSlot  = int(t3.x);           // -1 = casts no shadow
        }
        else
        {
            lightPos    = uLightPos[n];
            lightColor  = uLightColor[n].rgb;
            lightRadius = uLightRadius[n];
            spotDir     = uLightDir[n];
            isSpot      = uLightIsSpot[n] > 0.5;
            cosOuter    = uLightCosOuter[n];
            cosInner    = uLightCosInner[n];
            shadowSlot  = -1;
        }

        vec3  toLight = lightPos - vViewPos;
        float dist    = length(toLight);
        vec3  L       = toLight / dist;

        float atten = clamp(1.0 - (dist * dist) / (lightRadius * lightRadius), 0.0, 1.0);
        if (atten <= 0.0) continue;

        if (isSpot)
        {
            float cosAngle = dot(-L, spotDir);
            atten *= smoothstep(cosOuter, cosInner, cosAngle);
            if (atten <= 0.0) continue;
        }

        float NdotL = dot(N, L);

        // Pre-integrated scattering (Penner). The table holds, per channel, the
        // diffuse response of a curved skin surface where a Lambert term would
        // hold max(NdotL, 0) — so red bleeds past the terminator further than
        // green and blue, and the falloff softens as the surface curves. Sharp
        // features (nose, ears, knuckles) scatter most; flat cheeks barely.
        vec3 lambert = vec3(clamp(NdotL, 0.0, 1.0));
        vec3 scatter = texture2D(tSkinLUT, vec2(NdotL * 0.5 + 0.5, lutY)).rgb;
        vec3 diffuseTerm = mix(lambert, scatter, uSSSStrength * uHasSkinLUT);

        vec3 thisDiffuse  = lightColor * diffuseTerm * atten;
        vec3 thisSpecular = vec3(0.0);

        // Transmission through thin parts. With no thickness map on the asset,
        // curvature stands in for thinness — ears, fingers and the nose are the
        // sharply-curved bits, and they are also the ones that glow when a light
        // is behind them. Tint is fixed: it is blood, not albedo.
        // edgeFade again, explicitly: transmission is the most saturated term in
        // the shader and the one that showed as the red outline, so it does not
        // get to rely on lutY alone having been damped.
        float thin = smoothstep(0.45, 0.8, lutY) * edgeFade;
        float back = pow(clamp(dot(V, -L), 0.0, 1.0), 3.0) * thin;
        thisDiffuse += lightColor * vec3(0.85, 0.42, 0.34) * back * atten * uTransStrength;

        if (NdotL > 0.0 && roughness < 0.99)
        {
            vec3  H     = normalize(L + V);
            float NdotH = max(dot(N, H), 0.0);
            float VdotH = max(dot(V, H), 0.0);

            // Dual lobe: a broad one for the skin surface itself and a tight one
            // for the oil film on top. One lobe alone is what reads as polished
            // plastic — real skin has a soft sheen with a small sharp glint in it.
            float rBroad = max(roughness, 0.08);
            float rOil   = max(roughness * 0.45, 0.04);
            float D = D_GGX(NdotH, rBroad) * 0.85 + D_GGX(NdotH, rOil) * 0.15;
            float G = G_SmithSchlick(NdotV, max(NdotL, 0.0001), rBroad);
            vec3  F = F_Schlick(VdotH, F0);

            vec3 spec = (D * G * F) / max(4.0 * NdotV * NdotL, 0.001);
            thisSpecular = spec * lightColor * NdotL * atten * uSpecStrength;
        }

        if (shadowSlot >= 0 && uShadowRect[shadowSlot].w > 0.5)
        {
            float sf = shadowFactorPCF(vShadowClip[shadowSlot], uShadowRect[shadowSlot]);
            thisDiffuse  *= sf;
            thisSpecular *= sf;
        }

        diffuseAccum  += thisDiffuse;
        specularAccum += thisSpecular;
    }

    vec3 bakedLight = ((uHasLightmap > 0.5)
        ? pow(texture2D(tLightmap, vLightmapUV).rgb, vec3(2.2)) + uAmbientColor
        : uAmbientColor) * occlusion;

    if (uHasEnvMap > 0.5 && roughness < 0.99)
    {
        vec3 R_view  = reflect(-V, N);
        vec3 R_world = mat3(uCamRight, uCamUp, uCamForward) * R_view;
        vec2 envUV = vec2(
            atan(R_world.x, R_world.z) / (2.0 * PI),
            asin(clamp(-R_world.y, -1.0, 1.0)) / PI + 0.5
        );
        vec3  envSample = pow(textureLod(tEnvMap, envUV, roughness * 7.0).rgb, vec3(2.2));
        vec3  envF      = F_SchlickRoughness(NdotV, F0, roughness);
        float roughFade = (1.0 - roughness) * (1.0 - roughness);
        float ambientLum = dot(uAmbientColor, vec3(0.2126, 0.7152, 0.0722));
        // One extra (1 - roughness) over what phong_perpixel applies. Skin sits
        // at roughness ~0.5, where the shared damping still leaves a bright sky
        // ring around the silhouette that reads as a wet, waxy rim.
        specularAccum += envSample * envF * roughFade * (1.0 - roughness) * occlusion
                       * smoothstep(0.0, 0.05, ambientLum);
    }

    // No (1 - metallic) diffuse suppression: skin is a dielectric by definition.
    //
    // NOT max(bakedLight, diffuseAccum): that's a per-CHANNEL max, and skin's
    // diffuseAccum is chromatically lopsided (the scatter LUT bleeds red past
    // the terminator further than green/blue, and the transmission term adds a
    // fixed red-heavy tint). Through a partial-shadow band, the shadow factor
    // scales diffuseAccum down on all three channels evenly, but green/blue
    // cross below bakedLight's flat ambient before red does — so a per-channel
    // max keeps red from the still-bright diffuse term while green/blue fall
    // back to neutral ambient, producing a decoupled red fringe right at the
    // shadow transition. Compare by luminance and keep whichever source's
    // FULL colour is brighter, so channels never mix across the two sources.
    float diffuseLum = dot(diffuseAccum, vec3(0.2126, 0.7152, 0.0722));
    float bakedLum    = dot(bakedLight, vec3(0.2126, 0.7152, 0.0722));
    vec3 litColor = (diffuseLum > bakedLum) ? diffuseAccum : bakedLight;
    vec3 color = albedo * litColor + specularAccum;

    if (uHasEmissionMap > 0.5)
        color += pow(texture2D(tEmissionMap, animUV).rgb, vec3(2.2));

    // r_charshaderdebug: flat green on the skin buffer, magenta on the hair
    // ones. Answers "is this shader bound at all?" before any tuning question.
    if (uDebugTint > 0.5)
        color = vec3(0.0, 1.0, 0.0);

    gl_FragColor = vec4(applyLocalFog(color, vViewPos), 1.0);
}
